### ISSUE TITLE
Issues with NeoWX-Material on fresh install

### ISSUE THREAD

**Issue by magnum61** [neoground/neowx-material#2]
Hi,

i've just installed WeeWX fresh with latest version 4.4.0.1

The installation of the skin went through, but after the restart of weewx service i am getting some python errors in my syslog.
No idea how to fix that, might be something with the code

```
 weewx.cheetahgenerator: Generate failed with exception '<class 'TypeError'>'
 weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/neowx-material/index.html.tmpl
 weewx.cheetahgenerator: **** Reason: '>' not supported between instances of 'NoneType' and 'int'
 weewx.cheetahgenerator: ****  Traceback (most recent call last):
 weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 324, in generate
 weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
 weewx.cheetahgenerator: ****    File "_etc_weewx_skins_neowx_material_index_html_tmpl.py", line 1257, in respond
 weewx.cheetahgenerator: ****  TypeError: '>' not supported between instances of 'NoneType' and 'int'
 weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
 weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/neowx-material/almanac.html.tmpl
 weewx.cheetahgenerator: **** Reason: cannot find 'next_full_moon' while searching for 'almanac.next_full_moon.raw'
 weewx.cheetahgenerator: ****  Traceback (most recent call last):
 weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 324, in generate
 weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
 weewx.cheetahgenerator: ****    File "_etc_weewx_skins_neowx_material_almanac_html_tmpl.py", line 973, in respond
 weewx.cheetahgenerator: ****  NameMapper.NotFound: cannot find 'next_full_moon' while searching for 'almanac.next_full_moon.ra
```w'

Any support would be appreciated

**Comment by neoground** [comment]
Hi,

there was a bug in the barometer trend section. If the trend is None this error will be thrown. This is fixed in the next release (1.5) which will be released this weekend.

To manually fix this, update line 68 of `index.html.tmpl` (an if condition):

```
#if $trend.barometer.raw is not None and $trend.barometer.raw > 0
```

**Comment by Anderl94** [comment]
I had the same error. After I installed the Debian package "python3-ephem" it was gone.

**Comment by magnum61** [comment]
Thanks for your super fast response. I tried it first with the suggestion regarding python3-ephem and it worked!

Next step would have been the manual fix in index.html, but not needed.

What a great template. Thanks for that  work

**Comment by neoground** [comment]
Thanks for the ephem advice. I added a note in the installation guide.
