### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by groetg** [neoground/neowx-material#38]
I have troubles installing (How easy it should be), i've downloaded the ZIP file en put it on mu Rpi. 

Then:

"wee_extension --install=/home/pi/neowx-material-latest.zip
Request to install '/home/pi/neowx-material-latest.zip'
Extracting from zip archive /home/pi/neowx-material-latest.zip
Saving installer file to /usr/share/weewx/user/installer/neowx-material
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 88, in <module>
    main()
  File "/usr/share/weewx/wee_extension", line 80, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 125, in install_extension
    self.install_from_dir(extension_dir)
  File "/usr/share/weewx/weecfg/extension.py", line 228, in install_from_dir
    shutil.copy2(installer_path, extension_installer_dir)
  File "/usr/lib/python3.7/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/share/weewx/user/installer/neowx-material'"

**Comment by groetg** [comment]
I made a brand new install of my RPI and Weewx. Now at installing Neowx-material:

pi@raspberrypi:~ $ wee_extension --install=/home/pi/neowx-material.zip
Request to install '/home/pi/neowx-material.zip'
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 88, in <module>
    main()
  File "/usr/share/weewx/wee_extension", line 80, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 134, in install_extension
    raise InstallError("Extension '%s' not found." % extension_path)
weecfg.extension.InstallError: Extension '/home/pi/neowx-material.zip' not found

**Comment by groetg** [comment]
I saw a manual option to install the skin and that works!
