### ISSUE TITLE
After update weewx from 4.10.2 to 5.0.2 the report crashes 

### ISSUE THREAD

**Issue by sowasgeht** [neoground/neowx-material#87]
When debugging I find the following error message and don't know how to fix it, maybe someone has an idea?

weewxd[2267]: INFO weewx.engine: Shutting down StdReport thread
weewxd[2267]: ERROR weewx.engine: Unable to shut down StdReport thread
weewxd[2267]: DEBUG weewx.restx: Shut down MQTT thread.
weewxd[2267]: CRITICAL __main__: Database OperationalError exception: database is locked
weewxd[2267]: CRITICAL __main__:     ****  Waiting 2 minutes then retrying...
weewxd[2267]: ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx/skins/neowx-material/year-%Y.html.tmpl failed.
weewxd[2267]: ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/neowx-material/year-%Y.html.tmpl
weewxd[2267]: ERROR weewx.cheetahgenerator: **** Reason: cannot find 'format' while searching for 'format'
weewxd[2267]: ERROR weewx.cheetahgenerator: **** To debug, try inserting '#errorCatcher Echo' at top of template

**Comment by seehausen** [comment]
have you checked the latest version from fork https://github.com/seehase/neowx-material
there I did not saw this error

**Comment by sowasgeht** [comment]
No, I haven't tried it, I'll test it and give you feedback. Unfortunately I'm on the road at the moment and it could take a while.

**Comment by sowasgeht** [comment]
Unfortunately, the suggestion did not work The error message is still the same. See excerpt. There is then no report at all, I went back to the original, which crashes but makes a report about every 5 minutes.


ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx/skins/neowx-material/month-%Y-%m.html.tmpl failed.
Jun 16 14:40:17 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/neowx-material/month-%Y-%m.html.tmpl
Jun 16 14:40:17 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Reason: cannot find 'google_analytics_enable' while searching for 'Extras.Header.google_analytics_enable'
Jun 16 14:40:17 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** To debug, try inserting '#errorCatcher Echo' at top of template
Jun 16 14:40:18 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx/skins/neowx-material/year-%Y.html.tmpl failed.
Jun 16 14:40:18 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/neowx-material/year-%Y.html.tmpl
Jun 16 14:40:18 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Reason: cannot find 'google_analytics_enable' while searching for 'Extras.Header.google_analytics_enable'
Jun 16 14:40:18 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** To debug, try inserting '#errorCatcher Echo' at top of template
Jun 16 14:40:19 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx/skins/neowx-material/index.html.tmpl failed.
Jun 16 14:40:19 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/neowx-material/index.html.tmpl
Jun 16 14:40:19 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Reason: cannot find 'google_analytics_enable' while searching for 'Extras.Header.google_analytics_enable'
Jun 16 14:40:19 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** To debug, try inserting '#errorCatcher Echo' at top of template
Jun 16 14:40:19 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx/skins/neowx-material/yesterday.html.tmpl failed.
Jun 16 14:40:19 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/neowx-material/yesterday.html.tmpl
Jun 16 14:40:19 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Reason: cannot find 'google_analytics_enable' while searching for 'Extras.Header.google_analytics_enable'
Jun 16 14:40:19 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** To debug, try inserting '#errorCatcher Echo' at top of template
Jun 16 14:40:20 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx/skins/neowx-material/week.html.tmpl failed.
Jun 16 14:40:20 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/neowx-material/week.html.tmpl
Jun 16 14:40:20 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Reason: cannot find 'google_analytics_enable' while searching for 'Extras.Header.google_analytics_enable'
Jun 16 14:40:20 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** To debug, try inserting '#errorCatcher Echo' at top of template
Jun 16 14:40:20 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx/skins/neowx-material/month.html.tmpl failed.
Jun 16 14:40:20 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/neowx-material/month.html.tmpl
Jun 16 14:40:20 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Reason: cannot find 'google_analytics_enable' while searching for 'Extras.Header.google_analytics_enable'
Jun 16 14:40:20 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** To debug, try inserting '#errorCatcher Echo' at top of template
Jun 16 14:40:20 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx/skins/neowx-material/year.html.tmpl failed.
Jun 16 14:40:20 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/neowx-material/year.html.tmpl
Jun 16 14:40:21 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Reason: cannot find 'google_analytics_enable' while searching for 'Extras.Header.google_analytics_enable'
Jun 16 14:40:21 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** To debug, try inserting '#errorCatcher Echo' at top of template
Jun 16 14:40:21 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx/skins/neowx-material/archive.html.tmpl failed.
Jun 16 14:40:21 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/neowx-material/archive.html.tmpl
Jun 16 14:40:21 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Reason: cannot find 'google_analytics_enable' while searching for 'Extras.Header.google_analytics_enable'
Jun 16 14:40:21 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** To debug, try inserting '#errorCatcher Echo' at top of template
Jun 16 14:40:21 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx/skins/neowx-material/almanac.html.tmpl failed.
Jun 16 14:40:21 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/neowx-material/almanac.html.tmpl
Jun 16 14:40:21 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Reason: cannot find 'google_analytics_enable' while searching for 'Extras.Header.google_analytics_enable'
Jun 16 14:40:21 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** To debug, try inserting '#errorCatcher Echo' at top of template
Jun 16 14:40:21 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx/skins/neowx-material/telemetry.html.tmpl failed.
Jun 16 14:40:21 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/neowx-material/telemetry.html.tmpl
Jun 16 14:40:21 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** Reason: cannot find 'google_analytics_enable' while searching for 'Extras.Header.google_analytics_enable'
Jun 16 14:40:21 raspberrypi-Haus weewxd[712]: ERROR weewx.cheetahgenerator: **** To debug, try inserting '#errorCatcher Echo' at top of template
Jun 16 14:40:21 raspberrypi-Haus weewxd[712]: INFO weewx.cheetahgenerator: Generated 2 files for report StandardReport in 4.81 seconds
Jun 16 14:40:22 raspberrypi-Haus weewxd[712]: INFO weewx.reportengine: Copied 326 files to /var/www/html/weewx

**Comment by seehausen** [comment]
I will male a fresh installation with 5.0.2 
on a first run, I didn't saw this error

can you check your `skin.conf` file
it must contain in the section `[[Header]]`

```
        # Enable Google Analytics
        google_analytics_enable = no
        google_analytics_id =
```
or a valid config like

```
        # Enable Google Analytics
        google_analytics_enable = yes
        google_analytics_id = G-Xxxxxxx

```

**Comment by sowasgeht** [comment]
Is now inserted see error message:

        # Enable Google Analytics
        google_analytics_enable = no
        google_analytics_id =

LOG:
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: DEBUG weewx.reportengine: Running report 'StandardReport'
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: DEBUG weewx.reportengine: Found configuration file /etc/weewx/skins/neowx-material/skin.conf for report 'StandardReport'
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: DEBUG weewx.reportengine: Running generators for report 'StandardReport' in directory '/etc/weewx/skins/neowx-material'
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: DEBUG weewx.cheetahgenerator: Using search list ['user.historygenerator.MyXSearch', 'weewx.cheetahgenerator.Almanac', 'weewx.cheetahgenerator.Current', 'weewx.cheetahgenerator.DisplayOptions', 'weewx.cheetahgenerator.Extras', 'weewx.cheetahgenerator.Gettext', 'weewx.cheetahgenerator.JSONHelpers', 'weewx.cheetahgenerator.PlotInfo', 'weewx.cheetahgenerator.SkinInfo', 'weewx.cheetahgenerator.Station', 'weewx.cheetahgenerator.Stats', 'weewx.cheetahgenerator.UnitInfo']
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****  No module named 'user.historygenerator'
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 220, in run
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****      obj.start()
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 409, in start
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****      self.run()
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 163, in run
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****      self.init_extensions(gen_dict[section_name])
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 194, in init_extensions
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****      klass = weeutil.weeutil.get_object(x)
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weeutil/weeutil.py", line 1404, in get_object
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****      module = importlib.import_module(module_name)
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****    File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****      return _bootstrap._gcd_import(name[level:], package, level)
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****    File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****  ModuleNotFoundError: No module named 'user.historygenerator'
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: ERROR weewx.reportengine:         ****  Generator terminated
Jun 17 13:19:16 raspberrypi-Haus weewxd[727]: INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx

**Comment by seehausen** [comment]
I think you mixed old and new configuration in weewx.conf and skin.conf
probably during the upgrade process, the conf files are not consistent anymore

This new error shows that maybe histroygenerator is outdated
I would recommend setting up a clean fresh installation, or at lest take the latest sources from 
https://github.com/seehase/neowx-material
incl. /bin/user files

**Comment by sowasgeht** [comment]
Yes that's right I used the old weewx.conf and skin.conf!  With the skin.conf I have now used a new one, the weewx.conf I have to revise again probably the problems come from there. I will get back to you when I am ready.
